spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration
document:
  bucket-name: spring-boot-s3-poc
cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: XXX
      secret-key: XXXXX